
cd $REMOTE_ROOT
cd Na_mp-10172
test $? -ne 0 && exit 1
if [ ! -f 49a35700d054215d3b7ef34d2896fcb0843b90dc_task_tag_finished ] ;then
   ( ulimit -s unlimited && ulimit -l unlimited && export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so && export I_MPI_FABRICS=shm:ofi && export I_MPI_PMI=pmi && mpirun -n 64 vasp_std ) 1>>log 2>>err 
  if test $? -eq 0; then touch 49a35700d054215d3b7ef34d2896fcb0843b90dc_task_tag_finished; else echo 1 > $REMOTE_ROOT/28813827240f516f24be7c13e2763b4c2ea65585_flag_if_job_task_fail;tail -v -c 1000 $REMOTE_ROOT/Na_mp-10172/err > $REMOTE_ROOT/28813827240f516f24be7c13e2763b4c2ea65585_last_err_file;fi
fi &
wait 
