
cd $REMOTE_ROOT
cd Na3SbS4_mp-10167
test $? -ne 0 && exit 1
if [ ! -f c56f33f69b320ec35ec8f179f908e229e8ec8751_task_tag_finished ] ;then
   ( mpirun -np 64 vasp_std ) 1>>log 2>>err 
  if test $? -eq 0; then touch c56f33f69b320ec35ec8f179f908e229e8ec8751_task_tag_finished; else echo 1 > $REMOTE_ROOT/a5c06c2dee298919cdabeed26063c3c3f96e2724_flag_if_job_task_fail;tail -v -c 1000 $REMOTE_ROOT/Na3SbS4_mp-10167/err > $REMOTE_ROOT/a5c06c2dee298919cdabeed26063c3c3f96e2724_last_err_file;fi
fi &
wait 
