
cd $REMOTE_ROOT
cd Na3SbS4_mp-10167
test $? -ne 0 && exit 1
if [ ! -f d69bcce7fe970249dbdec0d542bb3b4ea25344fb_task_tag_finished ] ;then
   ( ulimit -s unlimited && ulimit -l unlimited && export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so && export I_MPI_FABRICS=shm:ofi && export I_MPI_PMI=pmi && mpirun -n 64 vasp_std ) 1>>log 2>>err 
  if test $? -eq 0; then touch d69bcce7fe970249dbdec0d542bb3b4ea25344fb_task_tag_finished; else echo 1 > $REMOTE_ROOT/e90bde71dcc413ce0e51910fef56595ef8a0c944_flag_if_job_task_fail;tail -v -c 1000 $REMOTE_ROOT/Na3SbS4_mp-10167/err > $REMOTE_ROOT/e90bde71dcc413ce0e51910fef56595ef8a0c944_last_err_file;fi
fi &
wait 
