#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 64
#SBATCH --gres=gpu:0
#SBATCH --partition 64c512g
#SBATCH --partition=64c512g
#SBATCH --mail-type=end
#SBATCH --mail-user=2393474010@sjtu.edu.cn
#SBATCH --ntasks=64
#SBATCH --time=48:00:00
#SBATCH --job-name=Na_AIMD


REMOTE_ROOT=$(readlink -f /dssg/home/acct-matxzl/matxzl/QiuQizhi/vasp_learn/Na_Na3SbS4_Data/AIMD_runs)
echo 0 > $REMOTE_ROOT/fec99ba51b5a5061b01c05141440c5fefe48bf38_flag_if_job_task_fail
test $? -ne 0 && exit 1


module load oneapi/2021.4.0





source $REMOTE_ROOT/fec99ba51b5a5061b01c05141440c5fefe48bf38.sub.run

cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat fec99ba51b5a5061b01c05141440c5fefe48bf38_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch fec99ba51b5a5061b01c05141440c5fefe48bf38_job_tag_finished; else exit 1;fi



