baseline:
  elemental:
    1: -2.6544
    6: -5.9724
model:
  lorem.Lorem:
    cutoff: 3.0
    initialize_node_features: true
    lr: true
    lr_kernel_type: "sog"
    sog_num_gaussians: 12
    sog_init_mode: "dimer_cc"
    sog_l_dependent_params: true
    max_degree: 6
