#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 64
#SBATCH --gres=gpu:0
#SBATCH --partition 64c512g
#SBATCH --partition=64c512g
#SBATCH --mail-type=end
#SBATCH --mail-user=2393474010@sjtu.edu.cn
#SBATCH --ntasks=64
#SBATCH --time=01:00:00
#SBATCH --job-name=E0_Calc


REMOTE_ROOT=$(readlink -f /dssg/home/acct-matxzl/matxzl/QiuQizhi/vasp_learn/Na_Na3SbS4_Data/E0_calcs)
echo 0 > $REMOTE_ROOT/86d2df369e8ea01ded00972075251977ddb44c57_flag_if_job_task_fail
test $? -ne 0 && exit 1


module load vasp/6.3.0-intel-2021.4.0





source $REMOTE_ROOT/86d2df369e8ea01ded00972075251977ddb44c57.sub.run

cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 86d2df369e8ea01ded00972075251977ddb44c57_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 86d2df369e8ea01ded00972075251977ddb44c57_job_tag_finished; else exit 1;fi



