#!/bin/bash -l
#SBATCH --parsable
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 16
#SBATCH --gres=gpu:1
#SBATCH --partition a100
#SBATCH --partition=a100
#SBATCH --gres=gpu:1
#SBATCH --mem=32G
#SBATCH --time=48:00:00
#SBATCH --job-name=MACE_Train
#SBATCH --mail-type=end
#SBATCH --mail-user=2393474010@sjtu.edu.cn


REMOTE_ROOT=$(readlink -f /dssg/home/acct-matxzl/matxzl/QiuQizhi/vasp_learn)
echo 0 > $REMOTE_ROOT/0a8901819275397a17cbeceae0ee7ca914e64552_flag_if_job_task_fail
test $? -ne 0 && exit 1







source $REMOTE_ROOT/0a8901819275397a17cbeceae0ee7ca914e64552.sub.run

cd $REMOTE_ROOT
test $? -ne 0 && exit 1

wait
FLAG_IF_JOB_TASK_FAIL=$(cat 0a8901819275397a17cbeceae0ee7ca914e64552_flag_if_job_task_fail)
if test $FLAG_IF_JOB_TASK_FAIL -eq 0; then touch 0a8901819275397a17cbeceae0ee7ca914e64552_job_tag_finished; else exit 1;fi



