
cd $REMOTE_ROOT
cd Interface_Gap1A_Compact_168atoms_continue
test $? -ne 0 && exit 1
if [ ! -f 1ab46b7f16c5067f76f09133a81323f8203faf6f_task_tag_finished ] ;then
   ( ulimit -s unlimited && ulimit -l unlimited && export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so && export I_MPI_FABRICS=shm:ofi && export I_MPI_PMI=pmi && mpirun -n 64 /dssg/opt/icelake/linux-centos8-icelake/oneapi-2021.4.0/vasp/vasp.6.3.0/bin/vasp_std ) 1>>log 2>>err 
  if test $? -eq 0; then touch 1ab46b7f16c5067f76f09133a81323f8203faf6f_task_tag_finished; else echo 1 > $REMOTE_ROOT/1c129794e991f09703f5bed74f53997621cfc1e5_flag_if_job_task_fail;tail -v -c 1000 $REMOTE_ROOT/Interface_Gap1A_Compact_168atoms_continue/err > $REMOTE_ROOT/1c129794e991f09703f5bed74f53997621cfc1e5_last_err_file;fi
fi &
wait 
