
cd $REMOTE_ROOT
cd Interface_Gap1A_Compact_168atoms
test $? -ne 0 && exit 1
if [ ! -f d3739f56d35da2b60106da6c26009c038bb266f3_task_tag_finished ] ;then
   ( ulimit -s unlimited && ulimit -l unlimited && export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so && export I_MPI_FABRICS=shm:ofi && export I_MPI_PMI=pmi && mpirun -n 64 /dssg/opt/icelake/linux-centos8-icelake/oneapi-2021.4.0/vasp/vasp.6.3.0/bin/vasp_std ) 1>>log 2>>err 
  if test $? -eq 0; then touch d3739f56d35da2b60106da6c26009c038bb266f3_task_tag_finished; else echo 1 > $REMOTE_ROOT/a09c58dc262e2d6575dc898a4845309a7e2f53d0_flag_if_job_task_fail;tail -v -c 1000 $REMOTE_ROOT/Interface_Gap1A_Compact_168atoms/err > $REMOTE_ROOT/a09c58dc262e2d6575dc898a4845309a7e2f53d0_last_err_file;fi
fi &
wait 
